<?php
// $Id: parser_csv.module,v 1.2.2.2 2009/02/22 16:29:19 alexb Exp $

/**
 * @file
 * Parse the incoming URL with SimpleXML into a FeedAPI compatible data structure.
 */

/**
 * Implementation of hook_help().
 */
function parser_csv_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('CSV Parser is a FeedAPI-compatible parser for CSV files. Requires PHP5. This parser expects commas , as a delimiter, no quotes around strings and a header in the first line of the CSV file.');
    case 'feedapi/full_name':
      return t('CSV Parser');
  }
}

/**
 * Implementation of hook_feedapi_feed().
 */
function parser_csv_feedapi_feed($op) {
  $args = func_get_args();
  switch ($op) {
    case 'type':
      // @todo: fix this
      return array("XML feed");
    case 'compatible':
      // @todo: determine compatibility.
      return TRUE;
    case 'parse':
      if (is_object($args[1])) {
        $feed = parser_csv_parse_feed($args[1]);
        return $feed;
      }
      break;
  }
}

/**
 * Parse document given at URL.
 *
 * @param $feed
 *   FeedAPI object.
 * @return parsed data as FeedAPI feed array
 */
function parser_csv_parse_feed($feed) {
  static $loaded = FALSE;
  if (!$loaded) {
    require(drupal_get_path('module', 'parser_csv') .'/parser_csv.inc');
    $loaded = TRUE;
  }
  return _parser_csv_parse_feed($feed);
}

/**
 * Implementation of hook_feedapi_settings_form().
 */
function parser_csv_feedapi_settings_form($type) {
  $form = array();
  switch ($type) {
    case 'parsers':
      $form['delimiter'] = array(
        '#type' => 'textfield',
        '#title' => t('Field delimiter'),
        '#default_value' => ',',
        '#description' => t('Enter a field delimiter (, or ;)'),
      );
  }
  return $form;
}

/**
 * Test function - parse a given file from tests/feeds/.
 * 
 * @param $file
 *   'test01.csv.ziptest' // Test zipped file loading and parsing.
 *   'test02.csv'; // Test double quote delimiters.
 *   'test03.csv'; // Test line breaks in double quote delimiters.
 */
function parser_csv_test($file) {
  $feed = new stdClass();
  $feed->url = url(drupal_get_path('module', 'parser_csv') .'/tests/feeds/'. $file, array('absolute' => TRUE));
  return parser_csv_parse_feed($feed);
}